V 02
anna-kireeshka/carsharing-app pull request #2
Opened 2022-03-01 20:47 UTC by anna-kireeshka

- Верстка первого шага оформления заказа
- хлебные крошки для роутов
- Переход по кнопке **Подробнее** к первому шагу заказа
- Переход по логотипу к главной странице

2022-03-04 16:58 UTC, e3Y6 requested changes
Добавлены комментарии.

2022-03-04 16:58 UTC, e3Y6 commented on src/components/BreadcrumbsRoute.vue
> +      v-for="(item, index) in breadCrumbs"
Порядок атрибутов лучше устанавливать согласно рекомендациям разработчиков Vue.

2022-03-04 16:58 UTC, e3Y6 commented on src/components/BreadcrumbsRoute.vue
> +            'navigation__link--disabled': breadCrumbs.length + 1 === index,
`breadCrumbs.length + 1 === index` лучше вынести в `<script>` и дать обозначение.

2022-03-04 20:40 UTC, anna-kireeshka commented on src/components/BreadcrumbsRoute.vue
> +            'navigation__link--disabled': breadCrumbs.length + 1 === index,
Не совсем пока то понимаю, как это будет работать при выносе в скрипт, пока что уберу. Сделаю стили перехода, когда добавятся другие роты

2022-03-05 08:03 UTC, e3Y6 requested changes
Добавлен идентификатор.

2022-03-05 08:03 UTC, e3Y6 commented on src/components/BreadcrumbsRoute.vue
> +        <router-link :to="item.to" class="navigation__link" id="a">{{
В БЭМ не используют селекторы идентификаторов.

2022-03-05 08:05 UTC, e3Y6 commented on src/components/BreadcrumbsRoute.vue
> +            'navigation__link--disabled': breadCrumbs.length + 1 === index,
Можно вынести в переменную или вычисляемое свойство.

2022-03-05 15:40 UTC, anna-kireeshka commented on src/components/BreadcrumbsRoute.vue
> +        <router-link :to="item.to" class="navigation__link" id="a">{{
Забыла удалить, использовала когда пробовала перенести в стили навигации в компьютед, чтобы потом найти элемент и добавлять на него стили

2022-03-10 07:10 UTC, e3Y6 approved these changes

2022-03-10 07:49 UTC, merged